-- Coach-LLM proposals — operator-reviewable suggestions for style edits.
-- Generated by proposeStyleEdits() reading recent self-play losses.
-- Status lifecycle:
--   pending   → waiting for operator review (default)
--   applied   → operator marked as applied to the style.json
--   dismissed → operator decided not to apply
--
-- Status changes are audit-logged via decided_by_admin_id + decided_at.
-- raw_output is kept only when JSON parse failed (debugging the LLM).
CREATE TABLE IF NOT EXISTS coach_proposals (
  id INTEGER PRIMARY KEY,
  style_slug TEXT NOT NULL,
  sample_size INTEGER NOT NULL,
  persona_filter TEXT,
  summary TEXT NOT NULL,
  edits_json TEXT NOT NULL,
  rationale_json TEXT NOT NULL,
  raw_output TEXT,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK(status IN ('pending','applied','dismissed')),
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  decided_at INTEGER,
  decided_by_admin_id INTEGER REFERENCES admins(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_coach_proposals_style
  ON coach_proposals(style_slug, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_coach_proposals_status
  ON coach_proposals(status, created_at DESC);
